name: Pull and Run Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  pull-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull shubhamgunjal23/netflixclone:latest

      - name: Run container
        run: docker run --rm shubhamgunjal23/netflixclone:latest
